const challengeResult6 = [
  { id: 74, product_name: 'Northwind Traders Almonds' },
  { id: 34, product_name: 'Northwind Traders Beer' },
  { id: 6, product_name: 'Northwind Traders Boysenberry Spread' },
  { id: 85, product_name: 'Northwind Traders Brownie Mix' },
  { id: 4, product_name: 'Northwind Traders Cajun Seasoning' },
  { id: 86, product_name: 'Northwind Traders Cake Mix' },
  { id: 1, product_name: 'Northwind Traders Chai' },
  { id: 91, product_name: 'Northwind Traders Cherry Pie Filling' },
  { id: 99, product_name: 'Northwind Traders Chicken Soup' },
  { id: 48, product_name: 'Northwind Traders Chocolate' },
  { id: 19, product_name: 'Northwind Traders Chocolate Biscuits Mix' },
  { id: 41, product_name: 'Northwind Traders Clam Chowder' },
  { id: 43, product_name: 'Northwind Traders Coffee' },
  { id: 93, product_name: 'Northwind Traders Corn' },
  { id: 40, product_name: 'Northwind Traders Crab Meat' },
  { id: 8, product_name: 'Northwind Traders Curry Sauce' },
  { id: 51, product_name: 'Northwind Traders Dried Apples' },
  { id: 7, product_name: 'Northwind Traders Dried Pears' },
  { id: 80, product_name: 'Northwind Traders Dried Plums' },
  { id: 17, product_name: 'Northwind Traders Fruit Cocktail' },
  { id: 56, product_name: 'Northwind Traders Gnocchi' },
  { id: 82, product_name: 'Northwind Traders Granola' },
  { id: 92, product_name: 'Northwind Traders Green Beans' },
  { id: 81, product_name: 'Northwind Traders Green Tea' },
  { id: 97, product_name: 'Northwind Traders Hot Cereal' },
  { id: 65, product_name: 'Northwind Traders Hot Pepper Sauce' },
  { id: 52, product_name: 'Northwind Traders Long Grain Rice' },
  { id: 20, product_name: 'Northwind Traders Marmalade' },
  { id: 72, product_name: 'Northwind Traders Mozzarella' },
  { id: 77, product_name: 'Northwind Traders Mustard' },
  { id: 5, product_name: 'Northwind Traders Olive Oil' },
  { id: 89, product_name: 'Northwind Traders Peaches' },
  { id: 88, product_name: 'Northwind Traders Pears' },
  { id: 94, product_name: 'Northwind Traders Peas' },
  { id: 90, product_name: 'Northwind Traders Pineapple' },
  { id: 83, product_name: 'Northwind Traders Potato Chips' },
  { id: 57, product_name: 'Northwind Traders Ravioli' },
  { id: 21, product_name: 'Northwind Traders Scones' },
  { id: 96, product_name: 'Northwind Traders Smoked Salmon' },
  { id: 3, product_name: 'Northwind Traders Syrup' },
  { id: 87, product_name: 'Northwind Traders Tea' },
  { id: 66, product_name: 'Northwind Traders Tomato Sauce' },
  { id: 95, product_name: 'Northwind Traders Tuna Fish' },
  { id: 98, product_name: 'Northwind Traders Vegetable Soup' },
  { id: 14, product_name: 'Northwind Traders Walnuts' }
];

module.exports = challengeResult6;
