const challengeResult1 = [
  { product_name: 'Northwind Traders Chai' },
  { product_name: 'Northwind Traders Syrup' },
  { product_name: 'Northwind Traders Cajun Seasoning' },
  { product_name: 'Northwind Traders Olive Oil' },
  { product_name: 'Northwind Traders Boysenberry Spread' },
  { product_name: 'Northwind Traders Dried Pears' },
  { product_name: 'Northwind Traders Curry Sauce' },
  { product_name: 'Northwind Traders Walnuts' },
  { product_name: 'Northwind Traders Fruit Cocktail' },
  { product_name: 'Northwind Traders Chocolate Biscuits Mix' },
  { product_name: 'Northwind Traders Marmalade' },
  { product_name: 'Northwind Traders Scones' },
  { product_name: 'Northwind Traders Beer' },
  { product_name: 'Northwind Traders Crab Meat' },
  { product_name: 'Northwind Traders Clam Chowder' },
  { product_name: 'Northwind Traders Coffee' },
  { product_name: 'Northwind Traders Chocolate' },
  { product_name: 'Northwind Traders Dried Apples' },
  { product_name: 'Northwind Traders Long Grain Rice' },
  { product_name: 'Northwind Traders Gnocchi' },
  { product_name: 'Northwind Traders Ravioli' },
  { product_name: 'Northwind Traders Hot Pepper Sauce' },
  { product_name: 'Northwind Traders Tomato Sauce' },
  { product_name: 'Northwind Traders Mozzarella' },
  { product_name: 'Northwind Traders Almonds' },
  { product_name: 'Northwind Traders Mustard' },
  { product_name: 'Northwind Traders Dried Plums' },
  { product_name: 'Northwind Traders Green Tea' },
  { product_name: 'Northwind Traders Granola' },
  { product_name: 'Northwind Traders Potato Chips' },
  { product_name: 'Northwind Traders Brownie Mix' },
  { product_name: 'Northwind Traders Cake Mix' },
  { product_name: 'Northwind Traders Tea' },
  { product_name: 'Northwind Traders Pears' },
  { product_name: 'Northwind Traders Peaches' },
  { product_name: 'Northwind Traders Pineapple' },
  { product_name: 'Northwind Traders Cherry Pie Filling' },
  { product_name: 'Northwind Traders Green Beans' },
  { product_name: 'Northwind Traders Corn' },
  { product_name: 'Northwind Traders Peas' },
  { product_name: 'Northwind Traders Tuna Fish' },
  { product_name: 'Northwind Traders Smoked Salmon' },
  { product_name: 'Northwind Traders Hot Cereal' },
  { product_name: 'Northwind Traders Vegetable Soup' },
  { product_name: 'Northwind Traders Chicken Soup' }
];

module.exports = challengeResult1;
