const challengeResult5 = [
  {
    supplier_ids: '10',
    id: 5,
    product_code: 'NWTO-5',
    product_name: 'Northwind Traders Olive Oil',
    description: null,
    standard_cost: '16.0125',
    list_price: '21.3500',
    reorder_level: 10,
    target_level: 40,
    quantity_per_unit: '36 boxes',
    discontinued: 0,
    minimum_reorder_quantity: 10,
    category: 'Oil',
    attachments: expect.any(Buffer)
  },
  {
    supplier_ids: '2;6',
    id: 6,
    product_code: 'NWTJP-6',
    product_name: 'Northwind Traders Boysenberry Spread',
    description: null,
    standard_cost: '18.7500',
    list_price: '25.0000',
    reorder_level: 25,
    target_level: 100,
    quantity_per_unit: '12 - 8 oz jars',
    discontinued: 0,
    minimum_reorder_quantity: 25,
    category: 'Jams, Preserves',
    attachments: expect.any(Buffer)
  },
  {
    supplier_ids: '2',
    id: 7,
    product_code: 'NWTDFN-7',
    product_name: 'Northwind Traders Dried Pears',
    description: null,
    standard_cost: '22.5000',
    list_price: '30.0000',
    reorder_level: 10,
    target_level: 40,
    quantity_per_unit: '12 - 1 lb pkgs.',
    discontinued: 0,
    minimum_reorder_quantity: 10,
    category: 'Dried Fruit & Nuts',
    attachments: expect.any(Buffer)
  },
  {
    supplier_ids: '8',
    id: 8,
    product_code: 'NWTS-8',
    product_name: 'Northwind Traders Curry Sauce',
    description: null,
    standard_cost: '30.0000',
    list_price: '40.0000',
    reorder_level: 10,
    target_level: 40,
    quantity_per_unit: '12 - 12 oz jars',
    discontinued: 0,
    minimum_reorder_quantity: 10,
    category: 'Sauces',
    attachments: expect.any(Buffer)
  },
  {
    supplier_ids: '2;6',
    id: 14,
    product_code: 'NWTDFN-14',
    product_name: 'Northwind Traders Walnuts',
    description: null,
    standard_cost: '17.4375',
    list_price: '23.2500',
    reorder_level: 10,
    target_level: 40,
    quantity_per_unit: '40 - 100 g pkgs.',
    discontinued: 0,
    minimum_reorder_quantity: 10,
    category: 'Dried Fruit & Nuts',
    attachments: expect.any(Buffer)
  },
  {
    supplier_ids: '6',
    id: 17,
    product_code: 'NWTCFV-17',
    product_name: 'Northwind Traders Fruit Cocktail',
    description: null,
    standard_cost: '29.2500',
    list_price: '39.0000',
    reorder_level: 10,
    target_level: 40,
    quantity_per_unit: '15.25 OZ',
    discontinued: 0,
    minimum_reorder_quantity: 10,
    category: 'Canned Fruit & Vegetables',
    attachments: expect.any(Buffer)
  },
  {
    supplier_ids: '1',
    id: 19,
    product_code: 'NWTBGM-19',
    product_name: 'Northwind Traders Chocolate Biscuits Mix',
    description: null,
    standard_cost: '6.9000',
    list_price: '9.2000',
    reorder_level: 5,
    target_level: 20,
    quantity_per_unit: '10 boxes x 12 pieces',
    discontinued: 0,
    minimum_reorder_quantity: 5,
    category: 'Baked Goods & Mixes',
    attachments: expect.any(Buffer)
  },
  {
    supplier_ids: '2;6',
    id: 20,
    product_code: 'NWTJP-6',
    product_name: 'Northwind Traders Marmalade',
    description: null,
    standard_cost: '60.7500',
    list_price: '81.0000',
    reorder_level: 10,
    target_level: 40,
    quantity_per_unit: '30 gift boxes',
    discontinued: 0,
    minimum_reorder_quantity: 10,
    category: 'Jams, Preserves',
    attachments: expect.any(Buffer)
  },
  {
    supplier_ids: '1',
    id: 21,
    product_code: 'NWTBGM-21',
    product_name: 'Northwind Traders Scones',
    description: null,
    standard_cost: '7.5000',
    list_price: '10.0000',
    reorder_level: 5,
    target_level: 20,
    quantity_per_unit: '24 pkgs. x 4 pieces',
    discontinued: 0,
    minimum_reorder_quantity: 5,
    category: 'Baked Goods & Mixes',
    attachments: expect.any(Buffer)
  },
  {
    supplier_ids: '4',
    id: 34,
    product_code: 'NWTB-34',
    product_name: 'Northwind Traders Beer',
    description: null,
    standard_cost: '10.5000',
    list_price: '14.0000',
    reorder_level: 15,
    target_level: 60,
    quantity_per_unit: '24 - 12 oz bottles',
    discontinued: 0,
    minimum_reorder_quantity: 15,
    category: 'Beverages',
    attachments: expect.any(Buffer)
  }

];

module.exports = challengeResult5;
